### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by dstan11** [stakahashy/fingan#3]
Hi, I am trying to train the model. However, I don't know the exact data format. Could you provide some sample input data? Thanks a lot.

**Comment by stakahashy** [comment]
Hi, download the following link and place the data folder to the project.  
https://www.dropbox.com/sh/ki25r44b6ioemut/AADVVsaF-pfKhYNzF83ZTLCUa?dl=0

**Comment by dstan11** [comment]
Great!
